import WidgetKit
import SwiftUI
import Foundation
import AppKit

// MARK: - Data

struct HudSnapshot {
    struct AgentInfo {
        let name: String
        let project: String
        let ctxPct: Double?
        let model: String?
        let session5hPct: Double?
        let week7dPct: Double?
        let activeTokens: UInt64
        let lastTurn: Date?
    }
    let active: AgentInfo?
    let agents: [AgentInfo]
    let generatedAt: Date

    static let empty = HudSnapshot(active: nil, agents: [], generatedAt: Date())

    static let appGroupID = "DQJT5BCZCM.com.htahaozlu.contextbar"

    static func load() -> HudSnapshot {
        let fm = FileManager.default
        var candidates: [URL] = []
        if let groupURL = fm.containerURL(forSecurityApplicationGroupIdentifier: appGroupID) {
            candidates.append(groupURL.appendingPathComponent("hud.json"))
        }
        candidates.append(URL(fileURLWithPath: "\(NSHomeDirectory())/.context-bar/hud.json"))

        var loaded: Data?
        for url in candidates {
            if let data = try? Data(contentsOf: url) {
                loaded = data
                break
            }
        }
        guard
            let data = loaded,
            let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return .empty }

        let claude = parse(root["claude"] as? [String: Any], name: "Claude")
        let codex = parse(root["codex"] as? [String: Any], name: "Codex")
        let all = [claude, codex].compactMap { $0 }
        let active = all.max(by: {
            ($0.lastTurn ?? .distantPast) < ($1.lastTurn ?? .distantPast)
        })
        return HudSnapshot(active: active, agents: all, generatedAt: Date())
    }

    private static func parse(_ raw: [String: Any]?, name: String) -> AgentInfo? {
        guard let raw else { return nil }
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let isoNoFrac = ISO8601DateFormatter()
        isoNoFrac.formatOptions = [.withInternetDateTime]
        let lastTurn: Date? = (raw["last_turn_at"] as? String).flatMap {
            iso.date(from: $0) ?? isoNoFrac.date(from: $0)
        }
        let cwd = raw["last_cwd"] as? String ?? ""
        let project = cwd.isEmpty ? "—" : (cwd as NSString).lastPathComponent
        return AgentInfo(
            name: name,
            project: project,
            ctxPct: raw["last_context_pct"] as? Double,
            model: raw["last_model"] as? String,
            session5hPct: raw["session_5h_percent"] as? Double,
            week7dPct: raw["week_7d_percent"] as? Double,
            activeTokens: (raw["active_session_tokens"] as? UInt64)
                ?? UInt64(raw["active_session_tokens"] as? Int ?? 0),
            lastTurn: lastTurn
        )
    }
}

// MARK: - Timeline

struct HudEntry: TimelineEntry {
    let date: Date
    let snapshot: HudSnapshot
}

struct HudProvider: TimelineProvider {
    func placeholder(in context: Context) -> HudEntry {
        HudEntry(date: Date(), snapshot: .empty)
    }
    func getSnapshot(in context: Context, completion: @escaping (HudEntry) -> Void) {
        completion(HudEntry(date: Date(), snapshot: HudSnapshot.load()))
    }
    func getTimeline(in context: Context, completion: @escaping (Timeline<HudEntry>) -> Void) {
        let now = Date()
        let snap = HudSnapshot.load()
        let entry = HudEntry(date: now, snapshot: snap)
        // Refresh every minute — hud.json is regenerated by the menubar app
        // far more often than that; this is the floor.
        let next = now.addingTimeInterval(60)
        completion(Timeline(entries: [entry], policy: .after(next)))
    }
}

// MARK: - Views

private func ctxColor(_ pct: Double?) -> Color {
    guard let pct else { return .secondary }
    switch pct {
    case ..<60: return .green
    case ..<85: return .orange
    default:    return .red
    }
}

private func fmtPct(_ v: Double?) -> String {
    guard let v else { return "—" }
    return String(format: "%.0f%%", v)
}

struct RingView: View {
    let value: Double?
    let label: String
    let tint: Color

    var body: some View {
        ZStack {
            Circle().stroke(Color.secondary.opacity(0.15), lineWidth: 6)
            Circle()
                .trim(from: 0, to: CGFloat(min(max((value ?? 0) / 100.0, 0), 1)))
                .stroke(tint, style: StrokeStyle(lineWidth: 6, lineCap: .round))
                .rotationEffect(.degrees(-90))
            VStack(spacing: 1) {
                Text(fmtPct(value))
                    .font(.system(size: 13, weight: .semibold, design: .rounded))
                    .monospacedDigit()
                Text(label)
                    .font(.system(size: 8, weight: .medium))
                    .foregroundColor(.secondary)
                    .textCase(.uppercase)
            }
        }
    }
}

struct BarRow: View {
    let label: String
    let value: Double?
    let tint: Color
    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack {
                Text(label).font(.system(size: 9, weight: .medium))
                    .foregroundColor(.secondary).textCase(.uppercase)
                Spacer()
                Text(fmtPct(value))
                    .font(.system(size: 10, weight: .semibold, design: .rounded))
                    .monospacedDigit()
                    .foregroundColor(tint)
            }
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule().fill(Color.secondary.opacity(0.12))
                    Capsule().fill(tint)
                        .frame(width: geo.size.width * CGFloat(min(max((value ?? 0) / 100, 0), 1)))
                }
            }
            .frame(height: 4)
        }
    }
}

struct SmallWidgetView: View {
    let entry: HudEntry
    var body: some View {
        let a = entry.snapshot.active
        ZStack {
            ContainerBackground()
            VStack(alignment: .leading, spacing: 8) {
                HStack(spacing: 6) {
                    Circle().fill(ctxColor(a?.ctxPct)).frame(width: 6, height: 6)
                    Text(a?.name ?? "no agent")
                        .font(.system(size: 11, weight: .semibold))
                    Spacer()
                }
                Text(a?.project ?? "—")
                    .font(.system(size: 14, weight: .bold, design: .rounded))
                    .lineLimit(1)
                    .truncationMode(.middle)
                Spacer(minLength: 0)
                RingView(value: a?.ctxPct, label: "context", tint: ctxColor(a?.ctxPct))
                    .frame(width: 56, height: 56)
                    .frame(maxWidth: .infinity, alignment: .center)
            }
            .padding(12)
        }
    }
}

struct MediumWidgetView: View {
    let entry: HudEntry
    var body: some View {
        let a = entry.snapshot.active
        ZStack {
            ContainerBackground()
            HStack(spacing: 14) {
                VStack(alignment: .leading, spacing: 6) {
                    HStack(spacing: 6) {
                        Circle().fill(ctxColor(a?.ctxPct)).frame(width: 6, height: 6)
                        Text(a?.name ?? "no agent")
                            .font(.system(size: 11, weight: .semibold))
                    }
                    Text(a?.project ?? "—")
                        .font(.system(size: 16, weight: .bold, design: .rounded))
                        .lineLimit(1).truncationMode(.middle)
                    if let m = a?.model {
                        Text(m).font(.system(size: 10))
                            .foregroundColor(.secondary).lineLimit(1)
                    }
                    Spacer(minLength: 0)
                    BarRow(label: "5h session", value: a?.session5hPct, tint: ctxColor(a?.session5hPct))
                    BarRow(label: "7d week", value: a?.week7dPct, tint: ctxColor(a?.week7dPct))
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                RingView(value: a?.ctxPct, label: "context", tint: ctxColor(a?.ctxPct))
                    .frame(width: 72, height: 72)
            }
            .padding(14)
        }
    }
}

struct LargeWidgetView: View {
    let entry: HudEntry
    var body: some View {
        ZStack {
            ContainerBackground()
            VStack(alignment: .leading, spacing: 12) {
                if let a = entry.snapshot.active {
                    HStack(alignment: .top, spacing: 12) {
                        VStack(alignment: .leading, spacing: 4) {
                            HStack(spacing: 6) {
                                Circle().fill(ctxColor(a.ctxPct)).frame(width: 7, height: 7)
                                Text(a.name).font(.system(size: 12, weight: .semibold))
                            }
                            Text(a.project)
                                .font(.system(size: 20, weight: .bold, design: .rounded))
                                .lineLimit(1).truncationMode(.middle)
                            if let m = a.model {
                                Text(m).font(.system(size: 11))
                                    .foregroundColor(.secondary)
                            }
                        }
                        Spacer()
                        RingView(value: a.ctxPct, label: "context", tint: ctxColor(a.ctxPct))
                            .frame(width: 64, height: 64)
                    }
                    Divider().opacity(0.4)
                    BarRow(label: "5h session", value: a.session5hPct, tint: ctxColor(a.session5hPct))
                    BarRow(label: "7d week", value: a.week7dPct, tint: ctxColor(a.week7dPct))
                } else {
                    Text("no agent")
                        .font(.system(size: 14)).foregroundColor(.secondary)
                }

                if entry.snapshot.agents.count > 1 {
                    Divider().opacity(0.4)
                    Text("All agents")
                        .font(.system(size: 9, weight: .semibold))
                        .foregroundColor(.secondary).textCase(.uppercase)
                    ForEach(entry.snapshot.agents.indices, id: \.self) { i in
                        let agent = entry.snapshot.agents[i]
                        HStack {
                            Circle().fill(ctxColor(agent.ctxPct)).frame(width: 5, height: 5)
                            Text(agent.name)
                                .font(.system(size: 11, weight: .medium))
                            Text("·").foregroundColor(.secondary)
                            Text(agent.project)
                                .font(.system(size: 11))
                                .foregroundColor(.secondary)
                                .lineLimit(1).truncationMode(.middle)
                            Spacer()
                            Text(fmtPct(agent.ctxPct))
                                .font(.system(size: 11, weight: .semibold, design: .rounded))
                                .monospacedDigit()
                                .foregroundColor(ctxColor(agent.ctxPct))
                        }
                    }
                }
                Spacer(minLength: 0)
            }
            .padding(16)
        }
    }
}

/// Wrapper that uses `containerBackground` on macOS 14+ and falls back to a
/// custom material fill on earlier systems. WidgetKit will reject widgets on
/// macOS 14+ that don't declare a container background.
struct ContainerBackground: View {
    var body: some View {
        if #available(macOS 14.0, *) {
            Color.clear
        } else {
            LinearGradient(
                colors: [Color(NSColor.windowBackgroundColor),
                         Color(NSColor.controlBackgroundColor)],
                startPoint: .topLeading, endPoint: .bottomTrailing
            )
        }
    }
}

struct WidgetEntryView: View {
    @Environment(\.widgetFamily) var family
    var entry: HudEntry
    var body: some View {
        Group {
            switch family {
            case .systemSmall: SmallWidgetView(entry: entry)
            case .systemMedium: MediumWidgetView(entry: entry)
            case .systemLarge: LargeWidgetView(entry: entry)
            default: MediumWidgetView(entry: entry)
            }
        }
        .modifier(WidgetBackgroundModifier())
    }
}

struct WidgetBackgroundModifier: ViewModifier {
    func body(content: Content) -> some View {
        if #available(macOS 14.0, *) {
            content.containerBackground(for: .widget) {
                LinearGradient(
                    colors: [Color(NSColor.windowBackgroundColor),
                             Color(NSColor.controlBackgroundColor)],
                    startPoint: .topLeading, endPoint: .bottomTrailing
                )
            }
        } else {
            content
        }
    }
}

// MARK: - Widget declaration

@main
struct ContextBarWidget: Widget {
    let kind: String = "ContextBarWidget"
    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: HudProvider()) { entry in
            WidgetEntryView(entry: entry)
        }
        .configurationDisplayName("ContextBar")
        .description("Active agent, project, and context usage.")
        .supportedFamilies([.systemSmall, .systemMedium, .systemLarge])
    }
}
